name: 🐍 Generate Snake

on:
  schedule:
    - cron: "15 1 * * *" # 6:45 AM IST
    - cron: "15 13 * * *" # 6:45 PM IST
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: gautham-here
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
